import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import {
  getSoftFactors,
  getQuestionsBySoftFactorId,
  postAnswer,
  getAnswersbyUsername,
} from "./softfactorAPI";

const initialState = {
  loading: false,
  softFactors: [],
  questions: [],
  answers: [],
  answersLoading: false,
  questionsAnswered: false,
  message: null,
  error: null,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getSF = createAsyncThunk(
  "softfactor/getSoftFactors",
  async (thunkAPI) => {
    const response = await getSoftFactors();
    return await response.json();
  }
);

export const getQuestionsBySFId = createAsyncThunk(
  "softfactor/getQuestionsBySoftFactorId",
  async (params, thunkAPI) => {
    const response = await getQuestionsBySoftFactorId(params.id);
    return await response.json();
  }
);

export const answerPost = createAsyncThunk(
  "softfactor/answerPost",
  async (params, thunkAPI) => {
    const response = await postAnswer(params.answers);
    const json = await response.json();
    return { status: response.status, ...json };
  }
);

export const getSFAnswersByUsername = createAsyncThunk(
  "softfactor/getSFAnswersByUsername",
  async (username, thunkAPI) => {
    const response = await getAnswersbyUsername(username);
    const json = await response.json();
    return { status: response.status, ...json };
  }
);

export const softfactorSlice = createSlice({
  name: "softfactor",
  initialState,
  reducers: {
    clearSoftFactorState(state) {
      state.loading = false;
      state.softFactors = [];
      state.questions = [];
      state.answers = [];
      state.answersLoading = false;
      state.questionsAnswered = false;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getSF.pending, (state) => {
        state.loading = true;
      })
      .addCase(getSF.fulfilled, (state, action) => {
        state.loading = false;
        if (action.payload.status) state.loading = false;
        else {
          state.softFactors = action.payload.item;
          state.loading = false;
        }
      })
      .addCase(getSF.rejected, (state) => {
        state.loading = false;
        state.error = "Something went wrong! Please try again later.";
      });
    builder
      .addCase(getQuestionsBySFId.pending, (state) => {
        state.loading = true;
        state.message = null;
      })
      .addCase(getQuestionsBySFId.fulfilled, (state, action) => {
        state.loading = false;
        if (action.payload.status) state.loading = false;
        else {
          state.questions = action.payload.item;
          state.message = action.payload.message;
          state.loading = false;
        }
      })
      .addCase(getQuestionsBySFId.rejected, (state) => {
        state.loading = false;
        state.error = "Something went wrong! Please try again later.";
      });
    builder
      .addCase(answerPost.pending, (state) => {
        state.loading = true;
        state.error = null;
        state.message = null;
      })
      .addCase(answerPost.fulfilled, (state, action) => {
        console.log(action.payload);
        state.loading = false;
        if (action.payload.status === 200) {
          state.questionsAnswered = true;
          state.message = action.payload.message;
          state.loading = false;
        } else {
          state.error = action.payload.message;
        }
      })
      .addCase(answerPost.rejected, (state) => {
        state.loading = false;
        state.error = "Something went wrong! Please try again later.";
      });
    builder
      .addCase(getSFAnswersByUsername.pending, (state) => {})
      .addCase(getSFAnswersByUsername.fulfilled, (state, action) => {
        if (action.payload.status === 200) {
          state.answers = action.payload.item;
        } else {
        }
      });
  },
});

// Action creators are generated for each case reducer function
export const { clearSoftFactorState } = softfactorSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`

export const selectSoftFactors = (state) => state.softfactor.softFactors;
export const selectQuestions = (state) => state.softfactor.questions;
export const selectQuestionsAnswered = (state) =>
  state.softfactor.questionsAnswered;
export const selectMessage = (state) => state.softfactor.message;
export const selectError = (state) => state.softfactor.error;
export const postMessage = (state) => state.softfactor.message;
export const selectAnswersLoading = (state) => state.softfactor.answersLoading;
export const selectAnswers = (state) => state.softfactor.answers;

export default softfactorSlice.reducer;
