import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import {
  delUser,
  fetchCandidates,
  fetchCompanies,
  setAnsweredQuestionnaire,
  updUser,
} from "./userAPI";

const initialState = {
  loading: false,
  processing: false,
  selectedUser: null,
  message: null,
  error: null,
  candidates: [],
  companies: [],
  questionnaireAnsweredSet: false,
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const getCandidates = createAsyncThunk(
  "user/getCandidates",
  async () => {
    const response = await fetchCandidates();
    // The value we return becomes the `fulfilled` action payload
    const json = await response.json();
    return json;
  }
);

export const getCompanies = createAsyncThunk("user/getCompanies", async () => {
  const response = await fetchCompanies();
  // The value we return becomes the `fulfilled` action payload
  const json = await response.json();
  return json;
});

export const updateUser = createAsyncThunk(
  "user/updateUser",
  async (params) => {
    const response = await updUser(params.id, params.updatedUser);
    const text = await response.text();
    // // The value we return becomes the `fulfilled` action payload
    if (response.ok) return { text, updatedUser: params.updatedUser };
  }
);

export const deleteUser = createAsyncThunk("user/deleteUser", async (id) => {
  const response = await delUser(id);
  const text = await response.text();
  // // The value we return becomes the `fulfilled` action payload
  if (response.ok) return text;
});

export const setQuestionnaireAnswered = createAsyncThunk(
  "user/setQuestionnaireAnswered",
  async (username) => {
    const response = await setAnsweredQuestionnaire(username);
    const text = await response.text();
    if (response.ok) return text;
  }
);

export const userSlice = createSlice({
  name: "user",
  initialState,
  reducers: {
    clearUserState(state) {
      state.loading = false;
      state.processing = false;
      state.selectedUser = null;
      state.candidates = [];
      state.companies = [];
      state.questionnaireAnsweredSet = false;
    },
    userLoading(state) {
      if (!state.loading) state.loading = true;
    },
    selectUser(state, action) {
      state.selectedUser = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getCandidates.pending, (state) => {
        state.loading = true;
      })
      .addCase(getCandidates.fulfilled, (state, action) => {
        if (action.payload.status) state.loading = false;
        else {
          state.candidates = action.payload;
          state.loading = false;
        }
      });
    builder
      .addCase(getCompanies.pending, (state) => {
        state.loading = true;
      })
      .addCase(getCompanies.fulfilled, (state, action) => {
        if (action.payload.status) state.loading = false;
        else {
          state.companies = action.payload;
          state.loading = false;
        }
      });
    builder
      .addCase(updateUser.pending, (state) => {
        state.processing = true;
      })
      .addCase(updateUser.fulfilled, (state, action) => {
        state.candidates = [
          ...state.candidates.map((item) => {
            if (item.id !== action.payload.updatedUser.id) {
              // This isn't the item we care about - keep it as-is
              return item;
            }
            // Otherwise, this is the one we want - return an updated value
            return {
              ...item,
              ...action.payload.updatedUser,
            };
          }),
        ];
        state.companies = [
          ...state.companies.map((item) => {
            if (item.id !== action.payload.updatedUser.id) {
              // This isn't the item we care about - keep it as-is
              return item;
            }
            // Otherwise, this is the one we want - return an updated value
            return {
              ...item,
              ...action.payload.updatedUser,
            };
          }),
        ];
        state.processing = false;
        state.selectedUser = null;
      });
    builder
      .addCase(deleteUser.pending, (state) => {
        state.processing = true;
      })
      .addCase(deleteUser.fulfilled, (state, action) => {
        if (action.payload.status) state.processing = false;
        else {
          state.candidates = [
            ...state.candidates.filter((item) => {
              return item.id !== state.selectedUser.id;
            }),
          ];
          state.companies = [
            ...state.companies.filter((item) => {
              return item.id !== state.selectedUser.id;
            }),
          ];
          state.processing = false;
          state.selectedUser = null;
        }
      });
    builder.addCase(setQuestionnaireAnswered.fulfilled, (state, action) => {
      state.loading = false;
      if (action.payload.status) {
      } else {
        state.questionnaireAnsweredSet = true;
      }
    });
  },
});

// Action creators are generated for each case reducer function
export const { clearUserState, userLoading, selectUser } = userSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectUserLoading = (state) => state.user.loading;
export const selectUserProcessing = (state) => state.user.processing;
export const selectCandidates = (state) => state.user.candidates;
export const selectCompanies = (state) => state.user.companies;
export const selectMessage = (state) => state.user.message;
export const selectError = (state) => state.user.error;
export const selectSelectedUser = (state) => state.user.selectedUser;
export const selectQuestionnaireAnsweredSet = (state) =>
  state.user.questionnaireAnsweredSet;

export default userSlice.reducer;
