name: Cypress Tests
on:
  pull_request:
    branches: 
      - main
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Add serve
        run: npm install -g serve
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          wait-on: 'http://localhost:3000'
          start: npm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          start: serve -s build

